### ISSUE TITLE
V2 观光团到此一游！！

### ISSUE THREAD

**Issue by XhstormR** [wichie/icamera#1]
![123](https://cloud.githubusercontent.com/assets/10527522/16712290/80ec820e-46b5-11e6-96fc-1745e9db2f36.jpg)

**Comment by saintaugustinus** [comment]
![80ec820e-46b5-11e6-96fc-1745e9db2f36](https://cloud.githubusercontent.com/assets/3031225/16712400/e1dc6ea0-46b8-11e6-8645-9e3f34dfe6e5.jpg)

**Comment by saintaugustinus** [comment]
![80ec820e-46b5-11e6-96fc-1745e9db2f36](https://cloud.githubusercontent.com/assets/3031225/16712405/0062fa88-46b9-11e6-877a-fe2347ac92d8.jpg)

**Comment by Jackroyal** [comment]
v2观光团+1
![](https://cloud.githubusercontent.com/assets/3031225/16712405/0062fa88-46b9-11e6-877a-fe2347ac92d8.jpg)

**Comment by Barbery** [comment]
![卑鄙](https://cloud.githubusercontent.com/assets/3031225/16712405/0062fa88-46b9-11e6-877a-fe2347ac92d8.jpg)

**Comment by uuair** [comment]
![](https://cloud.githubusercontent.com/assets/3031225/16712405/0062fa88-46b9-11e6-877a-fe2347ac92d8.jpg)

**Comment by scusjs** [comment]
![](https://cloud.githubusercontent.com/assets/3031225/16712405/0062fa88-46b9-11e6-877a-fe2347ac92d8.jpg)
V2观光团+1

**Comment by MrHuxu** [comment]
![](https://cloud.githubusercontent.com/assets/3031225/16712405/0062fa88-46b9-11e6-877a-fe2347ac92d8.jpg)

**Comment by hiing** [comment]
![]([https://cloud.githubusercontent.com/assets/3031225/16712405/0062fa88-46b9-11e6-877a-fe2347ac92d8.jpg])

**Comment by masahoshiro** [comment]
![image](https://cloud.githubusercontent.com/assets/10095657/16713731/607496e6-46e3-11e6-874c-30e079ba0ffd.png)

**Comment by icreeperi** [comment]
![607496e6-46e3-11e6-874c-30e079ba0ffd](https://cloud.githubusercontent.com/assets/7888621/16714089/8752f6d8-46eb-11e6-90b2-5175ab3d03b8.png)

**Comment by tiancaiCC** [comment]
到此一游+1

![](https://cloud.githubusercontent.com/assets/7888621/16714089/8752f6d8-46eb-11e6-90b2-5175ab3d03b8.png)

**Comment by KoenChiu** [comment]
![V2EX](https://cloud.githubusercontent.com/assets/7888621/16714089/8752f6d8-46eb-11e6-90b2-5175ab3d03b8.png)

**Comment by xia0chun** [comment]
![](https://cloud.githubusercontent.com/assets/7888621/16714089/8752f6d8-46eb-11e6-90b2-5175ab3d03b8.png)

**Comment by Arnie97** [comment]
![666](https://cloud.githubusercontent.com/assets/7888621/16714089/8752f6d8-46eb-11e6-90b2-5175ab3d03b8.png)

**Comment by doresu** [comment]
v2观光团+1
![http://tu.zbgs.me/uploads/big/6aa309b4fe9c417dcc50820bd6a54cef.gif](http://tu.zbgs.me/uploads/big/6aa309b4fe9c417dcc50820bd6a54cef.gif)

**Comment by lijianying10** [comment]
V2观光团

![](https://cloud.githubusercontent.com/assets/7888621/16714089/8752f6d8-46eb-11e6-90b2-5175ab3d03b8.png)

**Comment by zhuziyi1989** [comment]
偷书不算偷。。。

**Comment by xuchenkai** [comment]
![](https://cloud.githubusercontent.com/assets/7888621/16714089/8752f6d8-46eb-11e6-90b2-5175ab3d03b8.png)

**Comment by tth1996** [comment]
# V2观光团
![](https://cloud.githubusercontent.com/assets/7888621/16714089/8752f6d8-46eb-11e6-90b2-5175ab3d03b8.png)

**Comment by hansnow** [comment]
![](https://cloud.githubusercontent.com/assets/7888621/16714089/8752f6d8-46eb-11e6-90b2-5175ab3d03b8.png)

**Comment by TakiGuan** [comment]
![](https://cloud.githubusercontent.com/assets/7888621/16714089/8752f6d8-46eb-11e6-90b2-5175ab3d03b8.png)

**Comment by peinhu** [comment]
真牛！

**Comment by Alexis374** [comment]
臭傻逼

**Comment by youxiachai** [comment]
V2观光团

**Comment by MurphyL** [comment]
V2观光团

**Comment by tamarous** [comment]
不清楚事情经过的朋友，可以看这条帖子：
http://www.v2ex.com/t/291499

**Comment by lancer26** [comment]
![image](https://cloud.githubusercontent.com/assets/5106228/16718311/7ac1898c-4751-11e6-8f6d-a6bf57fd940f.png)

**Comment by SamWanng** [comment]
![](https://cloud.githubusercontent.com/assets/5106228/16718311/7ac1898c-4751-11e6-8f6d-a6bf57fd940f.png)

**Comment by tth1996** [comment]
# [_**V2观光团来此一游**_](http://www.v2ex.com/t/291499)
![](https://cloud.githubusercontent.com/assets/5106228/16718311/7ac1898c-4751-11e6-8f6d-a6bf57fd940f.png)

**Comment by Jianwen-Zheng** [comment]
![](https://cloud.githubusercontent.com/assets/5106228/16718311/7ac1898c-4751-11e6-8f6d-a6bf57fd940f.png)

**Comment by iURWang** [comment]
![](http://ww1.sinaimg.cn/large/006tNbRwjw1f5q13copx5j30fk0cgaba)

**Comment by jackeyGao** [comment]
![](https://cloud.githubusercontent.com/assets/5106228/16718311/7ac1898c-4751-11e6-8f6d-a6bf57fd940f.png)

**Comment by AsanZhang** [comment]
https://www.v2ex.com/t/291499
观光团

**Comment by zymiboxpay** [comment]
https://cloud.githubusercontent.com/assets/5106228/16718311/7ac1898c-4751-11e6-8f6d-a6bf57fd940f.png

**Comment by forehalo** [comment]
抄袭狗司马
![](https://cloud.githubusercontent.com/assets/9331269/16726875/13c85bb2-4791-11e6-9ed3-18ee11eb277b.png)

**Comment by fghpdf** [comment]
不明真像的吃瓜群众

**Comment by edisonator** [comment]
![image](https://cloud.githubusercontent.com/assets/7287198/16753678/5521b792-481e-11e6-833f-6ab88b6c9acb.png)

**Comment by leewaycn** [comment]
看我issue 2 # ，居然 也回复了。
